mysql:
  # if disabled, the plugin will use automatically sqlite for single server setup
  enable: false
  host: 127.0.0.1
  port: 3306
  database: databaseName
  user: username
  password: YourSecretPassword
  ssl: false
  advanced:
    # Don't change any values here if you don't know what you're doing
    connectionPoolSize: 10
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    cachePrepStmts: true
    useServerPrepStmts: true
sounds:
  onSuccess:
    data: ENTITY_PLAYER_LEVELUP
    volume: 1.0
    pitch: 1.8
  onFailure:
    data: BLOCK_NOTE_BLOCK_BELL
    volume: 1.0
    pitch: 0.3